#!/usr/bin/env bash

# OSX or Linux realpath
# http://stackoverflow.com/a/18443300
realpath() {
    local _PWD="$(pwd)"
    cd "$(dirname "$1")"
    local _LINK="$(readlink "$(basename "$1")")"
    while [ "${_LINK}" ]; do
        cd "$(dirname "${_LINK}")"
        _LINK="$(readlink "$(basename "${1}")")"
    done
    local _REALPATH="${PWD}/$(basename "${1}")"
    REALPATH="${_REALPATH%/}"
    cd "${_PWD}"
    echo "${REALPATH}"
}

DIR_ROOT="$(dirname $(realpath "$0"))"
echo $DIR_ROOT
# DIR_ROOT="${HOME}/code/rprofile-init"
RED="\033[0;31m"
NC="\033[0m"

echo
read -p "Initialize .Rprofile within $(pwd)? " -n 1 -r
echo; echo

if [[ ${REPLY} =~ ^[Yy]$ ]]; then

    # check if .Rprofile exists
    if [ -f .Rprofile ]; then
        # check to see if ${DIR_ROOT}/Rprofile
        #   is a subset of .Rprofile
        # prevents appending to file repeatedly

        # from http://unix.stackexchange.com/a/114884
        first_cmp=$(diff --unchanged-line-format= --old-line-format= \
            --new-line-format='%L' "${DIR_ROOT}/Rprofile" ".Rprofile" | wc -l)
        second_cmp=$(diff --unchanged-line-format= --old-line-format= \
            --new-line-format='%L' ".Rprofile" "${DIR_ROOT}/Rprofile" | wc -l)

        if [ "$first_cmp" -eq "0" -o "$second_cmp" -eq "0" ]; then
            echo "${DIR_ROOT}/Rprofile is a subset of .Rprofile"
            echo -e "To prevent duplication, ${RED}not${NC} appending..."
            echo "    ${DIR_ROOT}/Rprofile to .Rprofile"
            echo
            # early exit
            exit 0
        else
            echo ".Rprofile already exists; appending..."
            echo "    ${DIR_ROOT}/Rprofile to $(pwd)/.Rprofile"
            echo
        fi
    else
        echo "Creating new .Rprofile at $(pwd)/.Rprofile..."
        echo "Copying ${DIR_ROOT}/Rprofile to $(pwd)/.Rprofile"
        echo
    fi

    cat "${DIR_ROOT}/Rprofile" >> .Rprofile
else
    echo "Please cd into the directory desired to initialize .Rprofile"
    echo
fi
